Defect r17 2 new business name updating for pervious periods
ONSdigital/rm-party-service-api pull request #10
Opened 2018-03-22 13:00 UTC by andrewmil

Add `collectionExerciseId` to `PartyCreationRequestDTO`

[Trello](https://trello.com/c/nakcH70j/161-defect-r172-if-the-business-name-is-updated-in-a-sample-for-the-next-period-it-is-historically-updating-the-business-name-for-pr)

2018-03-22 13:08 UTC, andrewmil commented
![](https://github.trello.services/images/mini-trello-icon.png) [Defect R_17_2 If the business name is updated in a sample for the next period it is historically updating the business name for previous periods](https://trello.com/c/nakcH70j/161-defect-r172-if-the-business-name-is-updated-in-a-sample-for-the-next-period-it-is-historically-updating-the-business-name-for-pr)

2018-03-22 13:31 UTC, madeye-matt requested changes
As discussed, if the party service doesn't require the collectionExerciseId then the minOccurs should be 0

2018-03-22 14:28 UTC, madeye-matt approved these changes
Looks fine now 👍

2018-03-23 08:28 UTC, tej99 approved these changes

2018-03-23 09:50 UTC, closed without merging